// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOzlyjsCk6L37PoIWqvF8Q8ud2ghxMIOk',
    appId: '1:596403152661:web:d7b111e363a0fa56ad6b1c',
    messagingSenderId: '596403152661',
    projectId: 'dcn-database',
    authDomain: 'dcn-database.firebaseapp.com',
    storageBucket: 'dcn-database.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBCOfxpn2RtfbRaACECyhD_WC7SkKVlAk',
    appId: '1:596403152661:android:8c718ab5578fe3c3ad6b1c',
    messagingSenderId: '596403152661',
    projectId: 'dcn-database',
    storageBucket: 'dcn-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfBvQc9hwTd1PgNNgzy3tCRvgTpXdfP6k',
    appId: '1:596403152661:ios:938c87ee3276a39fad6b1c',
    messagingSenderId: '596403152661',
    projectId: 'dcn-database',
    storageBucket: 'dcn-database.appspot.com',
    iosBundleId: 'com.example.dcnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfBvQc9hwTd1PgNNgzy3tCRvgTpXdfP6k',
    appId: '1:596403152661:ios:938c87ee3276a39fad6b1c',
    messagingSenderId: '596403152661',
    projectId: 'dcn-database',
    storageBucket: 'dcn-database.appspot.com',
    iosBundleId: 'com.example.dcnApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOzlyjsCk6L37PoIWqvF8Q8ud2ghxMIOk',
    appId: '1:596403152661:web:a2fc53871b288e40ad6b1c',
    messagingSenderId: '596403152661',
    projectId: 'dcn-database',
    authDomain: 'dcn-database.firebaseapp.com',
    storageBucket: 'dcn-database.appspot.com',
  );
}
